config/routes.rb
Rails.application.routes.draw do

  get 'home2/index2'

resources :songs
resources :artists
root 'hip#hop'  
get '/about' => 'hip#about'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many:songs

	validates :name, presence: true
	validates :name, uniqueness: { case_sensitive: false}
end

app/models/bear.rb
class Bear < ActiveRecord::Base
end

app/models/song.rb
class Song < ActiveRecord::Base
	belongs_to :artist

	validates :name, presence: true
	validates :name, uniqueness: {scope: :artist, case_sensitive: false}
	validates :artist_id, presence: true
	validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name)
    end
end

app/controllers/hip_controller.rb
class HipController < ApplicationController
  def hop
  	@songs = Song.order(rating: :desc).limit(5)
  end

  def about
  end
end

app/controllers/home2_controller.rb
class Home2Controller < ApplicationController
  def index2
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
    @artists = Artist.all
  end

  # GET /songs/1/edit
  def edit
    @artists = Artist.all
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :rating, :artist_id, :video)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/hip_helper.rb
module HipHelper
end

app/helpers/home2_helper.rb
module Home2Helper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :name, class: 'form-control', placeholder: 'Artist Name' %>
  </div>
  <div class="actions">
    <%= f.submit "New Artist", class: 'btn btn-default' %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Artists</h1>

<p>
  <%= link_to new_artist_path do %>
    <i class="glyphicon glyphicon-plus">Add</i>
  <% end %>

  <div class="row">
    <% @artists.each do |artist| %>
    <div class="col-md-6">
      <div class="well">
        <h2><%= link_to artist.name, artist %>
        </h2>
        <h4>
          <%= link_to edit_artist_path(artist) do 
            %>

        </h4> 
        <i class="glyphicon glyphicon-pencil">
      </i>

          <%= link_to artist, method: :delete, data: {confirm: 'Are you sure?'} do %>
                    
             <i class="glyphicon glyphicon-trash"></i>
         <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-md-12">
		<div class="well">
			<h1><%= @artist.name %></h1></div></div></div>

			<% @artist.songs.each do |song| %>
				<h4><%= link_to song.name, song %>
				</h4>
				<% end %>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

app/views/hip/about.html.erb
<h1>Hip#about</h1>
<p>Find me in app/views/hip/about.html.erb</p>

app/views/hip/hop.html.erb
<h1>Top 5 Jams</h1>

<div class="row">
	<% @songs.each do |song| %>
		<div class="col-md-12">
			<div class="well">
				<h1><%= link_to song.name %>
				</h1>
					<h3> 
   						<%= link_to song.artist.name, song.artist %>
   					</h3>
   					<h4>
						<% song.rating.times do %>
						<i class="glyphicon glyphicon-star"></i>
					<% end %>
				</h4>
			</div>
		</div>
		<% end %>
	</div>

app/views/home2/index2.html.erb
<h1>Welcome to Home page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Music</title>

<!-- Latest compiled and minified CSS -->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous"> -->

  <%= stylesheet_link_tag    "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" %>
  <%=stylesheet_link_tag'application', media: 'all', 'data-turbolinks-track' => true %>


  <!-- Latest compiled and minified JavaScript -->
<!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script> -->

<%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand"><i class= "glyphicon glyphicon-headphones"> </i> We be Jammin'</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li><%= link_to "Top 5 Jams", root_path %></li>
		  <li><%= link_to "Artists", artists_path %></li>
		  <li><%= link_to "Songs", songs_path %></li>
                </ul>
              </nav>
            </div>
          </div>
          <div class="inner cover">
            <%= yield %>
          </div>
          <div class="mastfoot">
            <div class="inner">
              <p>TTS 2016</p>
            </div>
          </div>
        </div>
      </div>
    </div>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :name, class: 'form-control', placeholder: 'Song Name' %>
  </div>
  
  <div class="form-group">
    <br>
    <%= f.select :rating, [1, 2, 3, 4, 5], {:include_blank => 'Select a rating'}, class: 'form-control' %>
  </div>
  
  <div class="form-group">
 
    <%= f.collection_select :artist_id, @artists, :id, :name, {:include_blank => 'Select an Artist'}, class: 'form-control' %>
  </div>

  <div class="form-group">
      <%= f.text_field :video, class: 'form-control', placeholder: 'Youtube Video Link' %>  

      </div>

  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Songs</h1>
  <p> 
    <%= link_to new_song_path do %>
      <i class="glyphicon glyphicon-plus"> Add</i>
    <% end %>

      <div class="row">
        <% @songs.each do |song| %>
          <div class="col-md-6">
            <div class="well">
              <h2><%= link_to song.name, song %></h2>
              <h4><%= song.artist.name %></h4>
              <h4>
                <%= song.rating.times do %>
                <i class="glyphicon glyphicon-star"></i>
                <% end %>
              </h4>
              <h5>
                <% link_to song.name, song %>
                <% if song.video.presence %>
                <small><i class="glyphicon glyphicon-play">
                </i>
                </small>
                <% end %>
              </h5>
                  <p>
                    <%= link_to edit_song_path(song) do %>
                      <i class="glyphicon glyphicon-pencil"></i>
                    <% end %>
                      <%= link_to song, method: :delete, data: {confirm: 'Are you sure?'} do %>
                        <%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %>
                        <i class="glyphicon glyphicon-trash"></i>
                      <% end %>
                  </p>
              </div>
          </div>
    <% end %>
</div>
  

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-md-12">
		<div class="well">
			<h1><%= @song.name %>
			</h1>
				<h3> 
   					<%= link_to @song.artist.name, @song.artist %>
   				</h3>

					<% @song.rating.times do |song| %>
					<i class="glyphicon glyphicon-star"></i>
				<% end %>
				<% if @song.video.presence %>
					<div class="video">
						<iframe width="560" height="315" src="<%= @song.video %>" frameborder="0" allowfullscreen></iframe>
					</div>
				<% end %>
		</div>
	</div>
</div>

						<%= link_to 'Edit', edit_song_path(@song) %> 
						<%= link_to 'Back', songs_path %>